name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fix workspace permissions
      run: |
        git config --global --add safe.directory /__w/Kjump/Kjump

    - name: Build with Buildozer
      run: buildozer --accept-root -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
        
